services:
  copyei_redis:
    container_name: copyei_redis
    image: redis:7.2-alpine3.20
    command: redis-server --requirepass Teste123!@#
    ports:
      - 6379:6379
    volumes:
      - copyei_redis:/data

  copyei_postgres:
    container_name: copyei_postgres
    image: postgres:16.3-alpine3.19
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Teste123!@#
      - POSTGRES_DB=copyei
    ports:
     - "5440:5432" 
    volumes:
      - copyei_postgres:/var/lib/postgresql/data

volumes:
  copyei_redis:
  copyei_postgres:
